# Generated by Django 4.1.6 on 2023-03-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Block',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Set',
            new_name='Timetable',
        ),
    ]
