# Generated by Django 4.1.6 on 2023-03-20 13:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_event_options_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.PositiveIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='interval',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)]),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='notes',
            field=models.CharField(default=None, max_length=240),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
