# Generated by Django 4.1.6 on 2023-03-20 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_day_alter_event_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='set',
            new_name='timetable',
        ),
    ]
